import React, { useState, useCallback } from 'react';
import {
  View,
  Text,
  StyleSheet,
  FlatList,
  TouchableOpacity,
  TextInput,
  ScrollView,
  RefreshControl,
  Modal,
  ActivityIndicator,
  Alert,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { usePharmacy } from '../context/PharmacyContext';
import Header from '../components/Header';
import { StatusBadge, StockDot, DashboardBanner } from '../components/SharedComponents';
import { COLORS, SPACING, RADIUS, SHADOWS, FONTS } from '../utils/theme';
import { Medication } from '../types';

const ICON_MAP: Record<string, string> = {
  'Tablets': '💊',
  'Syrups': '🧪',
  'Injections': '💉',
  'Topical': '🧴',
  'Inhalers': '🌬️',
};

const ICON_COLOR_MAP: Record<string, string> = {
  'Tablets': '#3B82F6',
  'Syrups': '#10B981',
  'Injections': '#F43F5E',
  'Topical': '#F59E0B',
  'Inhalers': '#8B5CF6',
};

type Props = {
  navigation: any;
};

const InventoryScreen: React.FC<Props> = ({ navigation }) => {
  const { medications, addMedication, updateMedication, deleteMedication, refreshData, loading, addOrder, suppliers } = usePharmacy();
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState<'all' | 'available' | 'low_stock' | 'out_of_stock' | 'expiring_soon' | 'predictions'>('all');
  const [showAddModal, setShowAddModal] = useState(false);
  const [selectedMed, setSelectedMed] = useState<Medication | null>(null);
  const [showAutoRefill, setShowAutoRefill] = useState(false);
  const [selectedSupplier, setSelectedSupplier] = useState('');
  const [creatingOrder, setCreatingOrder] = useState(false);
  const [orderSuccess, setOrderSuccess] = useState(false);

  const [form, setForm] = useState({
    name: '',
    category: '',
    stockQuantity: '',
    expiryDate: '',
    price: '',
    supplier: '',
    minStockLevel: '',
  });

  const getExpiryRisk = (expiryDate: string) => {
    try {
      const exp = new Date(expiryDate);
      const now = new Date();
      const diffMonths = (exp.getTime() - now.getTime()) / (1000 * 60 * 60 * 24 * 30);
      if (diffMonths < 0) return 'expired';
      if (diffMonths < 3) return 'high';
      if (diffMonths < 6) return 'medium';
      return 'low';
    } catch { return 'unknown'; }
  };

  const onRefresh = useCallback(async () => {
    await refreshData();
  }, [refreshData]);

  // Auto-refill computed data
  const lowStockMeds = medications.filter((m: Medication) =>
    m.stockQuantity <= (m.minStockLevel || 10) ||
    m.status === 'low_stock' ||
    m.status === 'out_of_stock'
  ).slice(0, 20);

  const totalOrderValue = lowStockMeds.reduce((acc: number, m: Medication) => {
    const reorderQty = Math.max((m.minStockLevel || 10) * 3 - m.stockQuantity, 1);
    return acc + (m.price * reorderQty);
  }, 0);

  const handleCreateAutoOrder = async () => {
    if (!selectedSupplier) return;
    setCreatingOrder(true);
    const items = lowStockMeds.map((m: Medication) => ({
      medicationId: m.id,
      medicationName: m.name,
      quantity: Math.max((m.minStockLevel || 10) * 3 - m.stockQuantity, 1),
      unitPrice: m.price,
      totalPrice: m.price * Math.max((m.minStockLevel || 10) * 3 - m.stockQuantity, 1),
    }));
    try {
      await addOrder({
        supplierName: selectedSupplier,
        medications: items,
        totalAmount: totalOrderValue,
        status: 'pending',
        expectedDelivery: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        notes: 'Auto-generated by Refill Predictions engine',
      });
      setOrderSuccess(true);
    } finally {
      setCreatingOrder(false);
    }
  };

  const filteredMeds = medications.filter(m => {
    const matchSearch = m.name.toLowerCase().includes(search.toLowerCase()) ||
      m.category.toLowerCase().includes(search.toLowerCase());
    
    let matchFilter = true;
    if (filter === 'all') matchFilter = true;
    else if (filter === 'available' || filter === 'low_stock' || filter === 'out_of_stock') {
      matchFilter = m.status === filter;
    } else if (filter === 'expiring_soon') {
      const risk = getExpiryRisk(m.expiryDate);
      matchFilter = risk === 'high' || risk === 'expired';
    }


    return matchSearch && matchFilter;
  });

  const handleAdd = () => {
    if (!form.name || !form.category || !form.stockQuantity) {
      Alert.alert('Error', 'Please fill in required fields (Name, Category, Stock Quantity)');
      return;
    }
    const qty = parseInt(form.stockQuantity);
    const minLevel = parseInt(form.minStockLevel) || 10;
    let status: Medication['status'] = 'available';
    if (qty === 0) status = 'out_of_stock';
    else if (qty < minLevel) status = 'low_stock';

    addMedication({
      name: form.name,
      category: form.category,
      description: '',
      stockQuantity: qty,
      minStockLevel: minLevel,
      unit: 'Units',
      expiryDate: form.expiryDate || 'N/A',
      batchNumber: `BTH-${Date.now()}`,
      price: parseFloat(form.price) || 0,
      supplier: form.supplier || 'Unknown',
      status,
      imageColor: '#E8F5E9',
    });
    setShowAddModal(false);
    setForm({ name: '', category: '', stockQuantity: '', expiryDate: '', price: '', supplier: '', minStockLevel: '' });
  };

  const handleDelete = (med: Medication) => {
    Alert.alert('Delete Medication', `Remove ${med.name} from inventory?`, [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Delete',
        style: 'destructive',
        onPress: () => deleteMedication(med.id),
      },
    ]);
  };

  const FilterChip: React.FC<{ label: string; value: typeof filter }> = ({ label, value }) => (
    <TouchableOpacity
      style={[styles.filterChip, filter === value && styles.filterChipActive]}
      onPress={() => setFilter(value)}
    >
      <Text style={[styles.filterChipText, filter === value && styles.filterChipTextActive]}>
        {label}
      </Text>
    </TouchableOpacity>
  );

  return (
    <View style={styles.container}>
      <Header
        title="Green Pharmacy"
        subtitle="Inventory Management"
        showBack
        onBack={() => navigation.goBack()}
        showHome
        onHome={() => navigation.navigate('RoleSelector')}
        showSearch={false}
        showNotification
      />
      <DashboardBanner screenName="Inventory Management" />

      <View style={styles.summarySection}>
        <View style={[styles.summaryCard, SHADOWS.sm]}>
          <View style={styles.summaryItem}>
            <Text style={styles.summaryValue}>{medications.length}</Text>
            <Text style={styles.summaryLabel}>Total Items</Text>
          </View>
          <View style={styles.summaryDivider} />
          <View style={styles.summaryItem}>
            <Text style={[styles.summaryValue, { color: COLORS.warning }]}>
              {medications.filter(m => m.status === 'low_stock').length}
            </Text>
            <Text style={styles.summaryLabel}>Low Stock</Text>
          </View>
          <View style={styles.summaryDivider} />
          <View style={styles.summaryItem}>
            <Text style={[styles.summaryValue, { color: COLORS.danger }]}>
              {medications.filter(m => m.status === 'out_of_stock').length}
            </Text>
            <Text style={styles.summaryLabel}>Out Stock</Text>
          </View>
        </View>

        {/* Feature 5: Smart Re-Ordering */}
        <TouchableOpacity 
          style={[styles.smartOrderBtn, SHADOWS.sm]}
          onPress={() => {
            setOrderSuccess(false);
            setSelectedSupplier(suppliers.length > 0 ? suppliers[0].name : '');
            setShowAutoRefill(true);
          }}
        >
          <Ionicons name="cart" size={18} color={COLORS.white} />
          <Text style={styles.smartOrderBtnText}>Auto-Refill Predictions</Text>
        </TouchableOpacity>
      </View>


      <View style={styles.searchWrapper}>
        <View style={[styles.searchBar, SHADOWS.sm]}>
          <Ionicons name="search-outline" size={18} color={COLORS.textLight} />
          <TextInput
            style={styles.searchInput}
            placeholder="Search medications..."
            placeholderTextColor={COLORS.textLight}
            value={search}
            onChangeText={setSearch}
          />
          {search.length > 0 && (
            <TouchableOpacity onPress={() => setSearch('')}>
              <Ionicons name="close-circle" size={18} color={COLORS.textLight} />
            </TouchableOpacity>
          )}
        </View>
        <TouchableOpacity style={styles.filterIcon} onPress={() => Alert.alert('Scanner', 'Active Scanner engine...')}>
          <Ionicons name="barcode-outline" size={24} color={COLORS.primary} />
        </TouchableOpacity>
      </View>

      <View style={styles.filterSection}>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filterContainer}>
          <FilterChip label="All" value="all" />
          <FilterChip label="Available" value="available" />
          <FilterChip label="Low Stock" value="low_stock" />
          <FilterChip label="Out of Stock" value="out_of_stock" />
          <FilterChip label="📅 Expiring" value="expiring_soon" />
        </ScrollView>
      </View>

      <View style={styles.sectionLabelRow}>
        <Text style={styles.sectionLabel}>
          {filter === 'expiring_soon' ? 'EXPIRY RISK HEATMAP' : 'INTELLIGENT INVENTORY'}
        </Text>
        <Text style={styles.sectionCount}>{filteredMeds.length} items</Text>
      </View>

      <FlatList
        data={filteredMeds}
        keyExtractor={item => item.id}
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
        refreshControl={<RefreshControl refreshing={loading} onRefresh={onRefresh} colors={[COLORS.primary]} />}
        renderItem={({ item: med }) => {
          const risk = getExpiryRisk(med.expiryDate);
          const isPredicted = med.stockQuantity < (med.minStockLevel || 10) * 1.5;
          
          // Realistic mock prediction: stock / (min/10) = days left
          const predictedDays = Math.max(1, Math.floor((med.stockQuantity / ((med.minStockLevel || 10) / 2))));

          return (
            <TouchableOpacity key={med.id} style={[styles.medCard, SHADOWS.sm]} onPress={() => setSelectedMed(med)} activeOpacity={0.9}>
              {isPredicted && (
                <View style={styles.aiBadge}>
                  <Ionicons name="sparkles" size={10} color={COLORS.white} />
                  <Text style={styles.aiBadgeText}>AI PREDICTION: RUN OUT IN {predictedDays} DAYS</Text>
                </View>
              )}
              <View style={styles.medCardRow}>
                <View style={[styles.medIcon, { backgroundColor: med.imageColor }]}>
                  <Text style={[styles.medIconText, { color: ICON_COLOR_MAP[med.category] || COLORS.primary }]}>
                    {ICON_MAP[med.category] || '●'}
                  </Text>
                </View>
                <View style={styles.medInfo}>
                  <View style={styles.medNameRow}>
                    <Text style={styles.medName}>{med.name}</Text>
                    <StockDot status={med.status} />
                  </View>
                  <View style={styles.tagsRow}>
                    <View style={styles.categoryChip}>
                      <Text style={styles.categoryText}>{med.category.toUpperCase()}</Text>
                    </View>
                    {/* Feature 4: Expiry Heatmap Tag (Only show High/Med/Expired) */}
                    {risk !== 'low' && risk !== 'unknown' && (
                      <View style={[styles.expiryTag, risk === 'high' || risk === 'expired' ? styles.expiryTagHigh : styles.expiryTagMed]}>
                        <Ionicons name="time-outline" size={10} color={COLORS.white} />
                        <Text style={styles.expiryTagText}>{risk === 'expired' ? 'EXPIRED' : `${risk.toUpperCase()} RISK`}</Text>
                      </View>
                    )}
                  </View>
                  <View style={styles.medDetailsRow}>
                    <View style={styles.medDetailItem}>
                      <Text style={styles.medDetailLabel}>STOCK</Text>
                      <Text style={styles.medDetailValue}>{med.stockQuantity} {med.unit}</Text>
                    </View>
                    <View style={styles.medDetailItem}>
                      <Text style={styles.medDetailLabel}>EXPIRY</Text>
                      <Text style={[styles.medDetailValue, risk === 'high' && { color: COLORS.danger }]}>{med.expiryDate}</Text>
                    </View>
                  </View>
                </View>
              </View>
            </TouchableOpacity>
          );
        }}
        ListEmptyComponent={
          <View style={styles.emptyState}>
            <Ionicons name="search" size={48} color={COLORS.border} />
            <Text style={styles.emptyTitle}>No matching items</Text>
          </View>
        }
      />

      <TouchableOpacity style={[styles.fab, SHADOWS.lg]} onPress={() => setShowAddModal(true)}>
        <Ionicons name="add" size={32} color={COLORS.white} />
      </TouchableOpacity>

      <Modal visible={showAddModal} animationType="slide" transparent>
        <View style={styles.modalOverlay}>
          <View style={styles.modalCard}>
            <View style={styles.modalHeader}>
              <Text style={styles.modalTitle}>Add Medication</Text>
              <TouchableOpacity onPress={() => setShowAddModal(false)}>
                <Ionicons name="close" size={24} color={COLORS.text} />
              </TouchableOpacity>
            </View>
            <ScrollView showsVerticalScrollIndicator={false}>
              {[
                { label: 'Name', key: 'name' },
                { label: 'Category', key: 'category' },
                { label: 'Stock Quantity', key: 'stockQuantity', keyboard: 'numeric' },
                { label: 'Min Stock Level', key: 'minStockLevel', keyboard: 'numeric' },
                { label: 'Price (EGP)', key: 'price', keyboard: 'numeric' },
                { label: 'Expiry Date (YYYY-MM-DD)', key: 'expiryDate' },
                { label: 'Supplier', key: 'supplier' },
              ].map(f => (
                <View key={f.key} style={styles.formField}>
                  <Text style={styles.formLabel}>{f.label}</Text>
                  <TextInput
                    style={styles.formInput}
                    value={(form as any)[f.key]}
                    onChangeText={txt => setForm({ ...form, [f.key]: txt })}
                    keyboardType={(f.keyboard as any) || 'default'}
                  />
                </View>
              ))}
              <TouchableOpacity style={styles.addBtn} onPress={handleAdd}>
                <Text style={styles.addBtnText}>Add Medication</Text>
              </TouchableOpacity>
              <View style={{ height: 40 }} />
            </ScrollView>
          </View>
        </View>
      </Modal>

      {/* ===== AUTO-REFILL PREDICTIONS MODAL ===== */}
      <Modal visible={showAutoRefill} animationType="slide" transparent onRequestClose={() => setShowAutoRefill(false)}>
        <View style={styles.modalOverlay}>
          <View style={styles.modalCard}>
            <View style={styles.modalHeader}>
              <View>
                <Text style={styles.modalTitle}>🤖 Auto-Refill Predictions</Text>
                <Text style={{ color: COLORS.textSecondary, fontSize: 12, marginTop: 2 }}>
                  {lowStockMeds.length} low-stock items detected
                </Text>
              </View>
              <TouchableOpacity onPress={() => setShowAutoRefill(false)}>
                <Ionicons name="close" size={24} color={COLORS.text} />
              </TouchableOpacity>
            </View>

            {orderSuccess ? (
              <View style={{ alignItems: 'center', paddingVertical: 40, gap: 12 }}>
                <Ionicons name="checkmark-circle" size={72} color={COLORS.success} />
                <Text style={{ fontSize: 18, fontWeight: '800', color: COLORS.text }}>Order Created!</Text>
                <Text style={{ color: COLORS.textSecondary, textAlign: 'center' }}>
                  Purchase order sent to {selectedSupplier}.{'\n'}Check the Orders screen to approve it.
                </Text>
                <TouchableOpacity
                  style={[styles.addBtn, { marginTop: 16, width: '100%' }]}
                  onPress={() => setShowAutoRefill(false)}
                >
                  <Text style={styles.addBtnText}>Done</Text>
                </TouchableOpacity>
              </View>
            ) : (
              <>
                {/* Supplier Selection */}
                <Text style={[styles.formLabel, { marginBottom: 8 }]}>Select Supplier</Text>
                <View style={{ flexDirection: 'row', gap: 8, marginBottom: 16 }}>
                  {suppliers.map(s => (
                    <TouchableOpacity
                      key={s.id}
                      style={{
                        flex: 1, padding: 10, borderRadius: RADIUS.md, alignItems: 'center',
                        backgroundColor: selectedSupplier === s.name ? COLORS.primary : COLORS.background,
                        borderWidth: 1, borderColor: selectedSupplier === s.name ? COLORS.primary : COLORS.border,
                      }}
                      onPress={() => setSelectedSupplier(s.name)}
                    >
                      <Text style={{ fontWeight: '700', color: selectedSupplier === s.name ? COLORS.white : COLORS.text }}>
                        {s.name}
                      </Text>
                      <Text style={{ fontSize: 11, color: selectedSupplier === s.name ? COLORS.white : COLORS.textSecondary }}>
                        ⭐ {s.rating}
                      </Text>
                    </TouchableOpacity>
                  ))}
                </View>

                {/* Items list */}
                <Text style={[styles.formLabel, { marginBottom: 8 }]}>
                  Items to Reorder ({lowStockMeds.length})
                </Text>
                <ScrollView style={{ maxHeight: 200, borderWidth: 1, borderColor: COLORS.divider, borderRadius: RADIUS.md, padding: 8 }} nestedScrollEnabled>
                  {lowStockMeds.map(m => {
                    const reorderQty = Math.max((m.minStockLevel || 10) * 3 - m.stockQuantity, 1);
                    return (
                      <View key={m.id} style={{ flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: COLORS.divider }}>
                        <View style={{ flex: 1 }}>
                          <Text style={{ fontWeight: '600', fontSize: 12 }} numberOfLines={1}>{m.name}</Text>
                          <Text style={{ color: COLORS.danger, fontSize: 11 }}>Stock: {m.stockQuantity} / Min: {m.minStockLevel || 10}</Text>
                        </View>
                        <View style={{ alignItems: 'flex-end' }}>
                          <Text style={{ fontWeight: '700', fontSize: 12 }}>×{reorderQty}</Text>
                          <Text style={{ color: COLORS.primary, fontSize: 11 }}>EGP {(m.price * reorderQty).toLocaleString()}</Text>
                        </View>
                      </View>
                    );
                  })}
                </ScrollView>

                {/* Total */}
                <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginTop: 12, paddingTop: 8, borderTopWidth: 2, borderTopColor: COLORS.divider }}>
                  <Text style={{ fontWeight: '800', color: COLORS.text }}>Total Order Value:</Text>
                  <Text style={{ fontWeight: '800', color: COLORS.primary }}>EGP {totalOrderValue.toLocaleString()}</Text>
                </View>

                {/* Create Button */}
                <TouchableOpacity
                  style={[styles.addBtn, { marginTop: 16, opacity: (!selectedSupplier || creatingOrder) ? 0.6 : 1 }]}
                  onPress={handleCreateAutoOrder}
                  disabled={!selectedSupplier || creatingOrder}
                >
                  {creatingOrder
                    ? <ActivityIndicator color={COLORS.white} />
                    : <Text style={styles.addBtnText}>Generate Purchase Order</Text>
                  }
                </TouchableOpacity>
              </>
            )}
          </View>
        </View>
      </Modal>
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  summarySection: {
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.md,
    backgroundColor: COLORS.white,
  },
  summaryCard: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.md,
    padding: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.divider,
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  summaryItem: { alignItems: 'center', flex: 1 },
  summaryDivider: { width: 1, height: 30, backgroundColor: COLORS.divider },
  summaryValue: { fontSize: FONTS.sizes.lg, fontWeight: '800', color: COLORS.text },
  summaryLabel: { fontSize: 10, color: COLORS.textSecondary, fontWeight: '600', marginTop: 4, textTransform: 'uppercase' },
  smartOrderBtn: {
    backgroundColor: COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: RADIUS.md,
    marginTop: SPACING.md,
    gap: 8,
  },
  smartOrderBtnText: {
    color: COLORS.white,
    fontWeight: '700',
    fontSize: 13,
  },

  searchWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    gap: SPACING.sm,
    backgroundColor: COLORS.white,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.background,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: 10,
    gap: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  searchInput: { flex: 1, fontSize: FONTS.sizes.base, color: COLORS.text },
  filterIcon: { padding: SPACING.sm },
  filterSection: {
    backgroundColor: COLORS.white,
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
  },
  filterContainer: { flexDirection: 'row', paddingVertical: 4, gap: 8 },
  filterChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: RADIUS.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  filterChipActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary, ...SHADOWS.sm },
  filterChipText: { fontSize: FONTS.sizes.sm, color: COLORS.textSecondary, fontWeight: '700' },
  filterChipTextActive: { color: COLORS.white },
  sectionLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.sm,
    marginTop: SPACING.md,
  },
  sectionLabel: { fontSize: 11, fontWeight: '900', color: COLORS.textLight, letterSpacing: 1.2 },
  sectionCount: { fontSize: 11, color: COLORS.textSecondary, fontWeight: '600' },
  content: { paddingHorizontal: SPACING.lg, paddingTop: SPACING.xs },
  medCard: { backgroundColor: COLORS.white, borderRadius: RADIUS.md, padding: SPACING.lg, marginBottom: SPACING.md },
  aiBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: COLORS.info,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: RADIUS.full,
    alignSelf: 'flex-start',
    marginBottom: 8,
  },
  aiBadgeText: { fontSize: 9, fontWeight: '800', color: COLORS.white, letterSpacing: 0.5 },
  tagsRow: { flexDirection: 'row', gap: 8, marginTop: 4, marginBottom: 8 },
  expiryTag: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8, paddingVertical: 2, borderRadius: RADIUS.sm },
  expiryTagHigh: { backgroundColor: COLORS.danger },
  expiryTagMed: { backgroundColor: COLORS.warning },
  expiryTagLow: { backgroundColor: COLORS.success },
  expiryTagText: { fontSize: 9, fontWeight: '700', color: COLORS.white },
  medCardRow: { flexDirection: 'row', gap: SPACING.md },
  medIcon: { width: 64, height: 64, borderRadius: RADIUS.md, justifyContent: 'center', alignItems: 'center' },
  medIconText: { fontSize: 32 },
  medInfo: { flex: 1 },
  medNameRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  medName: { fontSize: FONTS.sizes.md, fontWeight: '800', color: COLORS.text },
  categoryChip: { backgroundColor: COLORS.background, paddingHorizontal: 8, paddingVertical: 2, borderRadius: 4, alignSelf: 'flex-start' },
  categoryText: { fontSize: 9, color: COLORS.textSecondary, fontWeight: '700' },
  medDetailsRow: { flexDirection: 'row', gap: SPACING.lg, paddingTop: 8, borderTopWidth: 1, borderTopColor: COLORS.divider },
  medDetailItem: { flex: 1 },
  medDetailLabel: { fontSize: 8, color: COLORS.textLight, fontWeight: '700', marginBottom: 2 },
  medDetailValue: { fontSize: 11, color: COLORS.text, fontWeight: '700' },
  fab: {
    position: 'absolute',
    right: SPACING.xl,
    bottom: SPACING.xxl,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyState: { alignItems: 'center', paddingVertical: 60, gap: SPACING.md },
  emptyTitle: { fontSize: FONTS.sizes.md, color: COLORS.textSecondary },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalCard: { backgroundColor: COLORS.white, borderTopLeftRadius: RADIUS.xl, borderTopRightRadius: RADIUS.xl, padding: SPACING.xl, maxHeight: '85%' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: SPACING.lg },
  modalTitle: { fontSize: FONTS.sizes.xl, fontWeight: '800', color: COLORS.text },
  formField: { marginBottom: SPACING.md },
  formLabel: { fontSize: FONTS.sizes.sm, color: COLORS.textSecondary, fontWeight: '600', marginBottom: 6 },
  formInput: { borderWidth: 1.5, borderColor: COLORS.border, borderRadius: RADIUS.md, padding: SPACING.md, fontSize: FONTS.sizes.base, color: COLORS.text, backgroundColor: COLORS.background },
  addBtn: { backgroundColor: COLORS.primary, borderRadius: RADIUS.md, padding: SPACING.lg, alignItems: 'center', marginTop: SPACING.md },
  addBtnText: { color: COLORS.white, fontWeight: '700', fontSize: FONTS.sizes.md },
});

export default InventoryScreen;
